# Generated by Django 6.0.6 on 2026-07-08 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "mrn",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Medical Record Number"
                    ),
                ),
                ("hospitalization_number", models.CharField(blank=True, max_length=20)),
                ("name", models.CharField(max_length=120)),
                ("first_name", models.CharField(blank=True, max_length=60)),
                ("last_name", models.CharField(blank=True, max_length=60)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "sex",
                    models.IntegerField(
                        blank=True, choices=[(1, "Male"), (2, "Female")], null=True
                    ),
                ),
                ("age", models.FloatField(blank=True, null=True)),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=4,
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=60)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=30),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(blank=True, max_length=60),
                ),
                ("insurance_provider", models.CharField(blank=True, max_length=120)),
                ("insurance_number", models.CharField(blank=True, max_length=60)),
                ("admission_date", models.DateField(blank=True, null=True)),
                ("discharge_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Alive", "Alive"),
                            ("Dead", "Dead"),
                            ("Inpatient", "Inpatient"),
                            ("Outpatient", "Outpatient"),
                            ("Discharged", "Discharged"),
                        ],
                        max_length=15,
                    ),
                ),
                ("operation_date", models.DateField(blank=True, null=True)),
                ("diagnosis_pathological", models.IntegerField(blank=True, null=True)),
                ("diagnosis_etiological", models.IntegerField(blank=True, null=True)),
                ("diagnosis_coexisting", models.IntegerField(blank=True, null=True)),
                ("bmi", models.FloatField(blank=True, null=True)),
                ("meld_score", models.FloatField(blank=True, null=True)),
                ("child_pugh_score", models.IntegerField(blank=True, null=True)),
                (
                    "child_pugh_category",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=1,
                    ),
                ),
                ("cold_ischemia_time", models.IntegerField(blank=True, null=True)),
                ("warm_ischemia_time", models.IntegerField(blank=True, null=True)),
                ("operative_time", models.IntegerField(blank=True, null=True)),
                ("anhepatic_phase_time", models.IntegerField(blank=True, null=True)),
                ("intraoperative_bleeding", models.IntegerField(blank=True, null=True)),
                ("intubation_time", models.FloatField(blank=True, null=True)),
                ("icu_days", models.FloatField(blank=True, null=True)),
                ("postop_hospital_days", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bed",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_patient",
                        to="organizations.bed",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to="organizations.department",
                    ),
                ),
                (
                    "primary_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["patient_id"],
            },
        ),
        migrations.CreateModel(
            name="PatientTimepoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timepoint",
                    models.CharField(
                        choices=[
                            ("preop", "Pre-operative"),
                            ("surgery", "Intraoperative"),
                            ("week1", "Post-op Week 1"),
                            ("month1", "Post-op Month 1"),
                            ("year1", "Post-op Year 1"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("alt", models.FloatField(blank=True, null=True)),
                ("ast", models.FloatField(blank=True, null=True)),
                ("bilirubin", models.FloatField(blank=True, null=True)),
                ("ggt", models.FloatField(blank=True, null=True)),
                ("alp", models.FloatField(blank=True, null=True)),
                ("creatinine", models.FloatField(blank=True, null=True)),
                ("urea", models.FloatField(blank=True, null=True)),
                ("inr", models.FloatField(blank=True, null=True)),
                ("albumin", models.FloatField(blank=True, null=True)),
                ("wbc", models.FloatField(blank=True, null=True)),
                ("hemoglobin", models.FloatField(blank=True, null=True)),
                ("platelets", models.FloatField(blank=True, null=True)),
                ("meld_score", models.FloatField(blank=True, null=True)),
                ("child_pugh_score", models.IntegerField(blank=True, null=True)),
                ("child_pugh_category", models.CharField(blank=True, max_length=1)),
                ("tacrolimus_level", models.FloatField(blank=True, null=True)),
                ("rejection_episode", models.BooleanField(blank=True, null=True)),
                ("rejection_grade", models.CharField(blank=True, max_length=10)),
                ("notes", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timepoints",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Timepoint",
                "ordering": ["patient", "timepoint"],
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["status"], name="patients_pa_status_ca3fc5_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["primary_doctor"], name="patients_pa_primary_ca59f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["meld_score"], name="patients_pa_meld_sc_e05ed0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patienttimepoint",
            unique_together={("patient", "timepoint")},
        ),
    ]
