# Generated by Django 6.0.6 on 2026-07-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="preop_complications",
            field=models.TextField(
                blank=True, verbose_name="Pre-operative complications"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="rolf_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Recovery of Liver Function (days)"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="split_composition",
            field=models.TextField(
                blank=True, verbose_name="Split liver donor composition (C-SLT)"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="split_etiology",
            field=models.TextField(
                blank=True, verbose_name="Split liver recipient etiology (E-SLT)"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="transplant_type",
            field=models.CharField(
                choices=[
                    ("WLT", "Whole Liver Transplant"),
                    ("SLT", "Split Liver Transplant"),
                ],
                db_index=True,
                default="WLT",
                max_length=3,
            ),
        ),
    ]
