# Generated by Django 6.0.6 on 2026-07-08 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("lab", "Laboratory Result"),
                            ("diagnosis", "Diagnosis"),
                            ("prescription", "Prescription"),
                            ("imaging", "Imaging Study"),
                            ("procedure", "Procedure"),
                            ("note", "Clinical Note"),
                            ("vital", "Vital Signs"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_flagged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_events",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("admission", "Admission Note"),
                            ("progress", "Progress Note"),
                            ("discharge", "Discharge Summary"),
                            ("consult", "Consultation"),
                            ("procedure", "Procedure Note"),
                            ("followup", "Follow-up Note"),
                        ],
                        default="progress",
                        max_length=15,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_note",
                        to="clinical.clinicalevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Note",
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icd_code", models.CharField(blank=True, max_length=20)),
                ("description", models.CharField(max_length=300)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("complication", "Complication"),
                        ],
                        default="primary",
                        max_length=15,
                    ),
                ),
                ("onset_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosis",
                        to="clinical.clinicalevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnosis",
                "verbose_name_plural": "Diagnoses",
            },
        ),
        migrations.CreateModel(
            name="ImagingStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("ultrasound", "Ultrasound"),
                            ("ct", "CT Scan"),
                            ("mri", "MRI"),
                            ("xray", "X-Ray"),
                            ("biopsy", "Biopsy"),
                            ("pet", "PET Scan"),
                        ],
                        max_length=15,
                    ),
                ),
                ("body_part", models.CharField(blank=True, max_length=100)),
                ("findings", models.TextField(blank=True)),
                ("impression", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("mild", "Mild Abnormality"),
                            ("abnormal", "Abnormal"),
                            ("critical", "Critical Finding"),
                        ],
                        default="normal",
                        max_length=15,
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imaging_study",
                        to="clinical.clinicalevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imaging Study",
                "verbose_name_plural": "Imaging Studies",
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "panel",
                    models.CharField(
                        choices=[
                            ("liver", "Liver Function"),
                            ("renal", "Renal Function"),
                            ("coag", "Coagulation"),
                            ("hematology", "Hematology"),
                            ("full", "Full Panel"),
                        ],
                        default="full",
                        max_length=15,
                    ),
                ),
                ("alt", models.FloatField(blank=True, null=True)),
                ("ast", models.FloatField(blank=True, null=True)),
                ("bilirubin", models.FloatField(blank=True, null=True)),
                ("ggt", models.FloatField(blank=True, null=True)),
                ("alp", models.FloatField(blank=True, null=True)),
                ("creatinine", models.FloatField(blank=True, null=True)),
                ("urea", models.FloatField(blank=True, null=True)),
                ("inr", models.FloatField(blank=True, null=True)),
                ("albumin", models.FloatField(blank=True, null=True)),
                ("wbc", models.FloatField(blank=True, null=True)),
                ("hemoglobin", models.FloatField(blank=True, null=True)),
                ("platelets", models.FloatField(blank=True, null=True)),
                ("tacrolimus_level", models.FloatField(blank=True, null=True)),
                ("meld_score", models.FloatField(blank=True, null=True)),
                ("child_pugh_score", models.IntegerField(blank=True, null=True)),
                ("child_pugh_category", models.CharField(blank=True, max_length=1)),
                ("rejection_episode", models.BooleanField(blank=True, null=True)),
                ("rejection_grade", models.CharField(blank=True, max_length=10)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_result",
                        to="clinical.clinicalevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Result",
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=200)),
                ("dose", models.CharField(max_length=60)),
                ("frequency", models.CharField(max_length=60)),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("oral", "Oral"),
                            ("iv", "IV"),
                            ("sc", "Subcutaneous"),
                            ("im", "IM"),
                            ("topical", "Topical"),
                        ],
                        default="oral",
                        max_length=15,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("immunosuppressant", "Immunosuppressant"),
                            ("antiviral", "Antiviral"),
                            ("antibiotic", "Antibiotic"),
                            ("supportive", "Supportive"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription",
                        to="clinical.clinicalevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
            },
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("procedure_name", models.CharField(max_length=200)),
                ("procedure_code", models.CharField(blank=True, max_length=20)),
                ("operative_time", models.IntegerField(blank=True, null=True)),
                ("cold_ischemia_time", models.IntegerField(blank=True, null=True)),
                ("warm_ischemia_time", models.IntegerField(blank=True, null=True)),
                ("anhepatic_phase_time", models.IntegerField(blank=True, null=True)),
                ("intraoperative_bleeding", models.IntegerField(blank=True, null=True)),
                ("intubation_time", models.FloatField(blank=True, null=True)),
                ("icu_days", models.FloatField(blank=True, null=True)),
                ("postop_hospital_days", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure",
                        to="clinical.clinicalevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure",
            },
        ),
        migrations.CreateModel(
            name="VitalSigns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("systolic_bp", models.IntegerField(blank=True, null=True)),
                ("diastolic_bp", models.IntegerField(blank=True, null=True)),
                ("heart_rate", models.IntegerField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("oxygen_sat", models.FloatField(blank=True, null=True)),
                ("respiratory_rate", models.IntegerField(blank=True, null=True)),
                ("weight_kg", models.FloatField(blank=True, null=True)),
                ("height_cm", models.FloatField(blank=True, null=True)),
                ("pain_score", models.IntegerField(blank=True, null=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="clinical.clinicalevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vital Signs",
                "verbose_name_plural": "Vital Signs",
            },
        ),
        migrations.AddIndex(
            model_name="clinicalevent",
            index=models.Index(
                fields=["patient", "event_type"], name="clinical_cl_patient_943048_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalevent",
            index=models.Index(
                fields=["patient", "timestamp"], name="clinical_cl_patient_718697_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalevent",
            index=models.Index(
                fields=["is_flagged"], name="clinical_cl_is_flag_ac79c6_idx"
            ),
        ),
    ]
