# Generated by Django 6.0.6 on 2026-07-08 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinical", "0001_initial"),
        ("organizations", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("outpatient", "Outpatient Visit"),
                            ("labs", "Laboratory"),
                            ("imaging", "Imaging"),
                            ("biopsy", "Biopsy"),
                            ("mdt", "MDT Review"),
                            ("followup", "Follow-up"),
                            ("emergency", "Emergency"),
                        ],
                        default="outpatient",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="organizations.department",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment",
                        to="clinical.clinicalevent",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "ordering": ["scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "scheduled_at"],
                        name="appointment_doctor__2f3cbe_idx",
                    ),
                    models.Index(
                        fields=["patient", "scheduled_at"],
                        name="appointment_patient_42b596_idx",
                    ),
                    models.Index(
                        fields=["status"], name="appointment_status_8fe9d7_idx"
                    ),
                ],
            },
        ),
    ]
